name: anp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - geopandas=0.13.0
  - matplotlib=3.7.1
  - momepy=0.6.0
  - numpy=1.24.3
  - pandas=2.0.2
  - networkx=3.1
  - rasterio=1.4.2
  - scipy=1.10.1
  - shapely=2.0.6
  - osmnx=1.3.1.post0
  - openpyxl=3.1.2
  - sparqlwrapper=2.0.0
  - contextily=1.3.0
  - matplotlib-scalebar=3.8.1
  - fiona=1.9.6
  - mkl=2022.1.0
  - scikit-learn=1.2.2
