name: anp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - geopandas=0.13.0
  - matplotlib=3.7.1
  - momepy=0.6.0
  - numpy=1.24.3
  - pandas=2.0.2
  - networkx=3.1
  - rasterio=1.4.2
  - scipy=1.10.1
  - shapely=2.0.6
  - osmnx=1.3.1.post0
#  - rdflib=6.3.2
  - openpyxl=3.1.2
  - sparqlwrapper=2.0.0
  - plotly=5.15.0
  - contextily=1.3.0
  - matplotlib-scalebar=3.8.1
#  - seaborn=0.12.2
#  - matplotlib-venn=
  - textblob=0.15.3
#  - graphviz=12.0.0
  - conda-forge::fiona=1.9.6
